// Generated by CoffeeScript 1.6.3
module.exports = function(compound) {
  if (process.env.NODE_ENV === 'test') {
    return;
  }
  return process.on('uncaughtException', function(err) {
    console.error(err);
    return console.error(err.stack);
  });
};
