// Generated by CoffeeScript 1.6.3
var DataLock;

DataLock = (function() {
  function DataLock() {
    this.locks = {};
  }

  DataLock.prototype.isLock = function(lock) {
    return this.locks[lock];
  };

  DataLock.prototype.addLock = function(lock) {
    var _this = this;
    if (!this.isLock[lock]) {
      this.locks[lock] = true;
      return setTimeout(function() {
        if (_this.isLock(lock)) {
          return delete _this.locks[lock];
        }
      }, 2000);
    }
  };

  DataLock.prototype.removeLock = function(lock) {
    return delete this.locks[lock];
  };

  DataLock.prototype.runIfUnlock = function(lock, callback) {
    var handleCallback,
      _this = this;
    handleCallback = function() {
      if (_this.isLock(lock)) {
        return setTimeout(handleCallback, 10);
      } else {
        return callback();
      }
    };
    return handleCallback();
  };

  return DataLock;

})();

module.exports = function(compound) {
  var app;
  app = compound.app;
  return app.locker = new DataLock();
};
