// Generated by CoffeeScript 1.6.2
var DocType, db;

db = require('../helpers/db_connect_helper').db_connect();

module.exports = DocType = (function() {
  function DocType() {}

  DocType.prototype.initAllView = function(callback) {
    var _this = this;

    return db.get("_design/docType", function(err, res) {
      var design_doc, map;

      if (err && err.error === 'not_found') {
        map = function(doc) {
          if (doc.docType === "doctype") {
            return emit(doc._id, doc);
          }
        };
        design_doc = {};
        design_doc.all = {
          map: map.toString()
        };
        return db.save("_design/docType", design_doc, function(err, res) {
          if (err) {
            return callback(err);
          } else {
            return callback(null);
          }
        });
      } else {
        return callback(null);
      }
    });
  };

  DocType.prototype.getDocTypes = function(callback) {
    return this.initAllView(function(err) {
      var _this = this;

      if (err) {
        return callback(err);
      } else {
        return db.view('docType/all', function(err, res) {
          if (err) {
            return callback(err);
          } else {
            if (res.length > 0) {
              return callback(null, res);
            } else {
              return callback(null, new Error("No docType found"));
            }
          }
        });
      }
    });
  };

  return DocType;

})();
