// Generated by CoffeeScript 1.6.3
var db, encryption;

db = require('../helpers/db_connect_helper').db_connect();

encryption = require('./encryption');

exports.initPassword = function(callback) {
  var _this = this;
  if (process.env !== 'development') {
    db.view("bankaccess/all", {}, function(err, res) {
      if (!err) {
        return res.forEach(function(value) {
          var _this = this;
          if (value.password != null) {
            return encryption.decrypt(value.password, function(err, password) {
              if (password === value.password) {
                return encryption.encrypt(value.password, function(err, password) {
                  value.password = password;
                  return db.save(value.id, value, function(err, res, body) {});
                });
              }
            });
          }
        });
      }
    });
  }
  return callback();
};
