// Generated by CoffeeScript 1.6.3
module.exports = function(compound) {
  var app, express, fs;
  express = require('express');
  fs = require('fs');
  app = compound.app;
  return app.configure(function() {
    var format, logFile;
    app.enable('coffee');
    app.use(express.bodyParser({
      keepExtensions: true
    }));
    app.use(express.methodOverride());
    format = '\
            \\n \\033[33;22m :date \\033[0m\
            \\n \\033[37;1m :method \\033[0m \\033[30;1m :url \\033[0m\
            \\n  >>> perform\
            \\n  Send to client: :status\
            \\n  <<<  [:response-time ms]';
    if (process.env.NODE_ENV === "production") {
      logFile = fs.createWriteStream('./log/production.log', {
        flags: 'a'
      });
      app.use(express.logger({
        stream: logFile,
        format: format
      }));
    }
    if (process.env.NODE_ENV === "test") {
      process.env.TOKEN = "token";
    }
    return app.use(app.router);
  });
};
