// Generated by CoffeeScript 1.6.3
var async, checkDocType, createFilter, db, encryption, filter, randomString, request;

load('application');

async = require("async");

db = require('./helpers/db_connect_helper').db_connect();

checkDocType = require('./lib/token').checkDocType;

request = require('./lib/request');

filter = require('./lib/default_filter');

encryption = require('./lib/encryption');

before('permissions', function() {
  var auth,
    _this = this;
  auth = req.header('authorization');
  return checkDocType(auth, "device", function(err, appName, isAuthorized) {
    if (!appName) {
      err = new Error("Application is not authenticated");
      return send({
        error: err
      }, 401);
    } else if (!isAuthorized) {
      err = new Error("Application is not authorized");
      return send({
        error: err
      }, 403);
    } else {
      _this.appName = appName;
      return next();
    }
  });
});

before('lock request', function() {
  var _this = this;
  this.lock = "" + params.id;
  return app.locker.runIfUnlock(this.lock, function() {
    app.locker.addLock(_this.lock);
    return next();
  });
}, {
  only: ['remove']
});

after('unlock request', function() {
  return app.locker.removeLock(this.lock);
}, {
  only: ['remove']
});

before('get doc', function() {
  var _this = this;
  return db.get(params.id, function(err, doc) {
    if (err && err.error === "not_found") {
      app.locker.removeLock(_this.lock);
      return send({
        error: "not found"
      }, 404);
    } else if (err) {
      console.log("[Get doc] err: " + JSON.stringify(err));
      app.locker.removeLock(_this.lock);
      return send({
        error: err
      }, 500);
    } else if (doc != null) {
      _this.doc = doc;
      return next();
    } else {
      app.locker.removeLock(_this.lock);
      return send({
        error: "not found"
      }, 404);
    }
  });
}, {
  only: ['remove']
});

randomString = function(length) {
  var string;
  string = "";
  while (string.length < length) {
    string = string + Math.random().toString(36).substr(2);
  }
  return string.substr(0, length);
};

createFilter = function(id, callback) {
  var _this = this;
  return db.get("_design/" + id, function(err, res) {
    var designDoc, filterDocTypeFunction, filterFunction, filterName;
    if (err && err.error === 'not_found') {
      designDoc = {};
      filterFunction = filter.get(id);
      designDoc.filter = filterFunction;
      filterDocTypeFunction = filter.getDocType(id);
      designDoc.filterDocType = filterDocTypeFunction;
      return db.save("_design/" + id, {
        views: {},
        filters: designDoc
      }, function(err, res) {
        if (err) {
          console.log("[Definition] err: " + JSON.stringify(err));
          return callback(err.message);
        } else {
          return callback(null);
        }
      });
    } else if (err) {
      return callback(err.message);
    } else {
      designDoc = res.filters;
      filterName = id + "filter";
      filterFunction = filter.get(defaultFilter, id);
      designDoc.filter = filterFunction;
      return db.merge("_design/" + id, {
        filters: designDoc
      }, function(err, res) {
        if (err) {
          console.log("[Definition] err: " + JSON.stringify(err));
          return callback(err.message);
        } else {
          return callback(null);
        }
      });
    }
  });
};

action('create', function() {
  var device;
  device = {
    login: body.login,
    password: randomString(32),
    docType: "Device",
    configuration: {
      "File": "all",
      "Folder": "all"
    }
  };
  return db.view('device/byLogin', {
    key: device.login
  }, function(err, res) {
    var decryptedPassword;
    if (err) {
      return send({
        error: true,
        msg: err
      }, 500);
    } else if (res.length !== 0) {
      return send({
        error: true,
        msg: "This name is already used"
      }, 400);
    } else {
      decryptedPassword = device.password;
      return encryption.encrypt(device.password, function(err, password) {
        var _this = this;
        if (err != null) {
          send({
            error: err
          }, 500);
        } else {
          device.password = password;
        }
        return db.save(device, function(err, res) {
          return createFilter(res._id, function(err) {
            if (err) {
              return send({
                error: true,
                msg: err
              }, 500);
            } else {
              device.id = res._id;
              device.password = decryptedPassword;
              return send(device, 200);
            }
          });
        });
      });
    }
  });
});

action('remove', function() {
  var id, send_success,
    _this = this;
  send_success = function() {
    send({
      success: true
    }, 200);
    return app.feed.feed.removeListener("deletion." + params.id, send_success);
  };
  id = params.id;
  return db.remove("_design/" + id, function(err, res) {
    if (err) {
      console.log("[Definition] err: " + JSON.stringify(err));
      return send({
        error: true,
        msg: err.message
      }, 500);
    } else {
      return db.remove(id, _this.doc._rev, function(err, res) {
        if (err) {
          console.log("[Definition] err: " + JSON.stringify(err));
          return send({
            error: true,
            msg: err.message
          }, 500);
        } else {
          return app.feed.feed.on("deletion." + params.id, send_success);
        }
      });
    }
  });
});
